### ISSUE TITLE
Basic Explanation of how to use the plugin

### ISSUE THREAD

**Issue by Oudwins** [Darakah/obsidian-map#11]
It would be great if we could have a basic docs. Or at least an example of the plugin on a working workspace.

Otherwise people have to try reading the code to use it. I have tried cloning the repo and, without doing anything else, plugin can't be activated. I imagine I need to compile the TS.

TL:DR -> request for basic, incomplete, docs.

**Comment by Darakah** [comment]
Hello, 

I didn't provide a documentation for I made this plugin for my own vault and not for general users as it requires certain setup steps.

To get the current version to work:
(as you said you need to compile the `ts` file)
- download the project
- `cd`
- `npm i`
- `npm run dev` 

Then copy paste the `manifest.json`, `main.js` and `style.css` into a folder and place inside your plugins directory.

Then you need to specify the location of your base tile maps if you have them (otherwise the map would display as empty). It is this line, and it depends on the location on your system (and the way you generated your tiles). Have you worked with leaflet tiles before? 

https://github.com/Darakah/obsidian-map/blob/a39b7c3dd679eeae22cbb52903317c3aa79f51a2/src/constants.ts#L6

I will try to push the latest version that I have `0.4.0` later today or tomorrow. 
You are also welcome to write / push any documentation or improvements to the project, it is greatly welcomed. If you have any further questions, please let me know.

**Comment by Darakah** [comment]
Pushed the latest `0.4.0` version and created a release for it https://github.com/Darakah/obsidian-map/releases/tag/0.4.0

though to set the path to the base tiles you need to open the `main.js` and search for `app://local/Users/Data` and replace with whatever your path is.

**Comment by Oudwins** [comment]
I had tried the build command which gave me an error. Just tried the dev command and got another error. Any idea?
Error:

```
> Map@0.3.0 dev
> rollup --config rollup.config.js -w

[!] Error: Cannot find module 'svelte/compiler'
Require stack:
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup-plugin-svelte/index.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/rollup.config.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'svelte/compiler'
Require stack:
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup-plugin-svelte/index.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/rollup.config.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup/dist/shared/loadConfigFile.js
- /home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup-plugin-svelte/index.js:4:33)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .js] (/home/oudwin/Documents/obsidian_vaults/test/.obsidian/plugins/obsidian-map/node_modules/rollup/dist/shared/loadConfigFile.js:516:13)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
```

**Comment by Darakah** [comment]
Well, its pretty self explanatory, you are missing npm modules (in this case it is the svelte compiler). 

https://github.com/Darakah/obsidian-map/blob/635096f522c0df67081d782486756d7d5e649765/rollup.config.js#L1-L7

Make sure to run `npm i` to get the node modules installed for this project, then install globally any of the others that fail.

**Comment by Oudwins** [comment]
Fixed. You need to add svelte as a dev dependency. You probably have it installed globally which is why you don't get the error. 

`npm i` didn't fail to install any packages but the code still gave error. 

only after installing svelte as a dev dependency did it compile

current package.json
```
    "devDependencies": {
        "@rollup/plugin-commonjs": "^15.1.0",
        "@rollup/plugin-node-resolve": "^9.0.0",
        "@rollup/plugin-typescript": "^6.0.0",
        "@types/leaflet": "^1.5.23",
        "@types/node": "^14.14.2",
        "obsidian": "https://github.com/obsidianmd/obsidian-api/tarball/master",
        "rollup": "^2.32.1",
        "rollup-plugin-styles": "^3.14.1",
        "tslib": "^2.0.3",
        "typescript": "^4.0.3"
    },
```
